Verify duplicate sharding table names
apache/shardingsphere pull request #10130
Opened 2021-04-19 10:31 UTC by menghaoranss

refer #10123 .

2021-04-19 13:18 UTC, tristaZero requested changes

2021-04-19 13:18 UTC, tristaZero commented on shardingsphere-proxy/shardingsphere-proxy-backend/src/main/java/org/apache/shardingsphere/proxy/backend/exception/DuplicateTableException.java
> +public final class DuplicateTableException extends BackendException {
DuplicateTables

2021-04-19 13:18 UTC, tristaZero commented on shardingsphere-db-protocol/shardingsphere-db-protocol-core/src/main/java/org/apache/shardingsphere/db/protocol/error/CommonErrorCode.java
> +    DUPLICATE_TABLE(1113, "C1113", "Duplicate table name %s."),
Does `%s` represent multiple table names?

2021-04-20 03:53 UTC, menghaoranss commented on shardingsphere-db-protocol/shardingsphere-db-protocol-core/src/main/java/org/apache/shardingsphere/db/protocol/error/CommonErrorCode.java
> +    DUPLICATE_TABLE(1113, "C1113", "Duplicate table name %s."),
Yes, such as : 
```
ERROR 1113 (C1113): Duplicate table name [t_order_item,t_order].
```

2021-04-20 07:10 UTC, tristaZero approved these changes

2021-04-20 07:10 UTC, merged