Optimize java doc in ShardingRule class
apache/shardingsphere pull request #10474
Opened 2021-05-26 03:48 UTC by KSMASTERS

Fixes #10461.

Changes proposed in this pull request:
- Optimize java doc in ShardingRule class
-
-

2021-05-26 06:12 UTC, tristaZero commented
@KSMASTERS Hey, thanks for your contribution.

2021-05-26 07:08 UTC, strongduanmu requested changes

2021-05-26 07:08 UTC, strongduanmu commented on shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-common/src/main/java/org/apache/shardingsphere/sharding/rule/ShardingRule.java
> +     * Judge whether all logic tables belongs to binding encryptors.
@KSMASTERS What do you think of this? 

```java
/**
 * Judge whether all logic tables are binding encryptors or not.
 * 
 * @param logicTableNames logic table names
 * @return whether all logic tables are binding encryptors or not
 */
```

If you think it's good, please use similar expressions to modify the Java doc.

2021-05-26 08:15 UTC, closed without merging

2021-05-26 08:48 UTC, KSMASTERS commented
Can I just submit it directly?

2021-05-27 07:46 UTC, tristaZero commented
@KSMASTERS You mean PR? Sure, welcome.