Fixes #10673, execute DCL without use schema.
apache/shardingsphere pull request #11466
Opened 2021-07-23 07:19 UTC by RaigorJiang

Fixes #10673.

Changes proposed in this pull request:
The DCL statements will take the broadcast route without checking the current schema.  For now, DCL statements Include:
- AlterRoleStatement
- AlterUserStatement
- CreateRoleStatement
- CreateUserStatement
- DropRoleStatement
- DropUserStatement
- GrantStatement
- RevokeStatement
- SetRoleStatement

2021-07-24 09:51 UTC, tristaZero requested changes

2021-07-24 09:51 UTC, tristaZero commented on shardingsphere-infra/shardingsphere-infra-common/src/test/java/org/apache/shardingsphere/infra/metadata/mapper/CreateUserStatementEventMapperTest.java
> +
Please remove this redundant line.

2021-07-26 02:44 UTC, menghaoranss commented on shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/impl/MySQLDCLStatementSQLVisitor.java
> +        MySQLDropUserStatement result = new MySQLDropUserStatement();
Could use lambda instead of `for`?

2021-07-26 03:00 UTC, RaigorJiang commented on shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/impl/MySQLDCLStatementSQLVisitor.java
> +        MySQLDropUserStatement result = new MySQLDropUserStatement();
OK, I'll change it to lambda.

2021-07-26 03:59 UTC, menghaoranss approved these changes

2021-07-26 05:44 UTC, tristaZero approved these changes

2021-07-26 05:45 UTC, merged