For #10983，Optimize change history of Spring Boot Starter Configuration.
apache/shardingsphere pull request #13443
Opened 2021-11-03 11:57 UTC by yx9o

For #10983，Optimize change history of ShardingSphere-JDBC Spring Boot Starter Configuration.

2021-11-03 12:15 UTC, menghaoranss requested changes

2021-11-03 12:15 UTC, menghaoranss commented on docs/document/content/reference/api-change-history/shardingsphere-jdbc/spring-boot-starter.cn.md
> +spring.shardingsphere.rules.shadow.column= # 影子字段名称名称
duplicate words `名称`

2021-11-03 13:13 UTC, yx9o commented on docs/document/content/reference/api-change-history/shardingsphere-jdbc/spring-boot-starter.cn.md
> +spring.shardingsphere.rules.shadow.column= # 影子字段名称名称
> duplicate words `名称`

@menghaoranss Has been updated, please review, thank you.

2021-11-04 00:57 UTC, menghaoranss approved these changes

2021-11-04 00:58 UTC, merged