fix subquery table alias bug
apache/shardingsphere pull request #14006
Opened 2021-12-08 13:00 UTC by cheese8

Ref #13972

Changes proposed in this pull request:
- fix subquery table alias bug

2021-12-08 14:56 UTC, strongduanmu requested changes
@cheese8 Thank you for your great job. But can you fix the ci error first?

2021-12-10 00:58 UTC, strongduanmu requested changes

2021-12-10 00:58 UTC, strongduanmu commented on shardingsphere-features/shardingsphere-encrypt/shardingsphere-encrypt-core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/impl/EncryptProjectionTokenGenerator.java
> +    private void processWithFirstColumnProjection(final ColumnProjectionSegment columnSegment, final List<ColumnProjection> projections) {
@cheese8 Why add this special logic? Can you consider handling similar logic inside generateProjections?

2021-12-10 00:58 UTC, strongduanmu commented on shardingsphere-features/shardingsphere-encrypt/shardingsphere-encrypt-core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/impl/EncryptProjectionTokenGenerator.java
> +        List<ColumnProjection> result = new LinkedList<>();
@cheese8 Please use Collection and Iterator to get first element.

2021-12-10 00:58 UTC, strongduanmu commented on shardingsphere-test/shardingsphere-rewrite-test/src/test/resources/scenario/encrypt/case/select_for_query_with_cipher.xml
> +    <rewrite-assertion id="select_not_nested_subquery_in_table_segment2" db-types="MySQL">
@cheese8 Can we give him a more meaningful name? Instead of ending with 1, 2.

2021-12-21 07:39 UTC, tuichenchuxin commented on shardingsphere-features/shardingsphere-encrypt/shardingsphere-encrypt-core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/impl/EncryptProjectionTokenGenerator.java
> +        if (shorthand || null == column.getOwner()) {
column.getOwner() can delete.

2021-12-21 07:39 UTC, tuichenchuxin commented on shardingsphere-features/shardingsphere-encrypt/shardingsphere-encrypt-core/src/main/java/org/apache/shardingsphere/encrypt/rewrite/token/generator/impl/EncryptProjectionTokenGenerator.java
> -
Code style should be same.

2021-12-21 09:14 UTC, strongduanmu approved these changes

2021-12-21 09:15 UTC, merged