Eliminate the ambiguity of `Notice` in the `APM INTEGRATION` section of the document
apache/shardingsphere pull request #14305
Opened 2021-12-24 14:57 UTC by linghengqian

Fixes #13553.

Changes proposed in this pull request:
- Eliminate the ambiguity of `Notice` in the `APM INTEGRATION` section of the document.

2021-12-24 16:49 UTC, terrymanu requested changes
Please keep space between English and Chinese words.

2021-12-25 03:36 UTC, linghengqian commented
> Please keep space between English and Chinese words.

Ok,I made another modification.

2021-12-29 07:41 UTC, linghengqian commented
Do I need to make other changes?

2021-12-29 11:31 UTC, menghaoranss approved these changes

2021-12-29 11:37 UTC, terrymanu approved these changes

2021-12-29 11:37 UTC, merged