Upgrade to Guava 30.0-jre
apache/shardingsphere pull request #14314
Opened 2021-12-25 02:40 UTC by Ahoo-Wang

Fixes #14313 .

Changes proposed in this pull request:
- Upgrade to Guava 30.0-jre

2021-12-25 08:35 UTC, terrymanu commented
Does Guava 30.0-jre compatible with curator, netty, grpc and other dependencies?
Could you analyze the dependency tree of ShardingSphere?

2021-12-25 08:36 UTC, terrymanu requested changes
The other question is the license of new dependencies.
Cloud you analyze the licenses of guava's new dependencies?

2022-01-14 04:30 UTC, terrymanu commented
Hello, any update?

2022-01-14 05:46 UTC, Ahoo-Wang commented
I'm very sorry to reply you too late.

I checked https://github.com/google/guava/releases/tag/v30.0 ,And compare the code https://github.com/google/guava/compare/v29.0...v30.0,
`v30.0` has only made feature enhancements and no breaking changes, so there should be no problem with compatibility.

But another problem is that we still can't solve this problem by upgrading to to `Guava 30.0-jre` (just `@Deprecated` this method). Here is a discussion on https://github.com/google/guava/issues/4011.

2022-01-16 15:27 UTC, terrymanu commented
Ok, I just merge the upgrade.

2022-01-16 15:27 UTC, terrymanu approved these changes

2022-01-16 15:27 UTC, merged