Update SingleTableRuleTest.java
apache/shardingsphere pull request #14635
Opened 2022-01-09 10:09 UTC by zzs52

Add test cases for SingleTableRule #12215.

Changes proposed in this pull request:
-
-
-

2022-01-09 13:36 UTC, zzs52 commented
Hi,CI prompts me to have 1 Checkstyle violation.But I didn't check it out.Can you tell me where is the problem I would be grateful?

2022-01-10 00:12 UTC, strongduanmu commented
> Can

@zzs52 src/test/java/org/apache/shardingsphere/singletable/rule/SingleTableRuleTest.java:[154] (coding) VariableDeclarationUsageDistance: Distance between variable 'singleTableRule' declaration and its first usage is 4, but allowed 3.  Consider making that variable final if you still need to store its value in advance (before method calls that might have side effects on the original value).

2022-01-10 00:14 UTC, strongduanmu requested changes

2022-01-10 00:14 UTC, strongduanmu commented on shardingsphere-kernel/shardingsphere-single-table/shardingsphere-single-table-core/src/test/java/org/apache/shardingsphere/singletable/rule/SingleTableRuleTest.java
> -
@zzs52 Please keep indents consistent with the previous one.

2022-01-10 00:14 UTC, strongduanmu commented on shardingsphere-kernel/shardingsphere-single-table/shardingsphere-single-table-core/src/test/java/org/apache/shardingsphere/singletable/rule/SingleTableRuleTest.java
> +        Collection<String> singleTableNames = new ArrayList<>();
LinkedList may be better.

2022-01-10 00:14 UTC, strongduanmu commented on shardingsphere-kernel/shardingsphere-single-table/shardingsphere-single-table-core/src/test/java/org/apache/shardingsphere/singletable/rule/SingleTableRuleTest.java
> +        Collection<RouteMapper> tableMappers = new ArrayList<>();
Same problem.

2022-01-10 03:36 UTC, zzs52 commented on shardingsphere-kernel/shardingsphere-single-table/shardingsphere-single-table-core/src/test/java/org/apache/shardingsphere/singletable/rule/SingleTableRuleTest.java
> +        Collection<RouteMapper> tableMappers = new ArrayList<>();
> Same problem.

Thank you so much.

2022-01-10 05:56 UTC, strongduanmu requested changes

2022-01-10 05:56 UTC, strongduanmu commented on shardingsphere-kernel/shardingsphere-single-table/shardingsphere-single-table-core/src/test/java/org/apache/shardingsphere/singletable/rule/SingleTableRuleTest.java
> -
@zzs52 Please keep indents consistent with the previous one.

2022-01-10 10:18 UTC, strongduanmu approved these changes
@zzs52 Good job, please go ahead.

2022-01-10 10:18 UTC, merged

2022-01-10 10:22 UTC, zzs52 commented
> @zzs52 Good job, please go ahead.

Thanks for the encouragement, I will.