Add support for generate narayana config file when the first resource added on cluster mode
apache/shardingsphere pull request #15566
Opened 2022-02-22 06:20 UTC by jingshanglu

Ref #15405.

2022-02-22 07:16 UTC, LeeGuoPing commented on shardingsphere-kernel/shardingsphere-transaction/shardingsphere-transaction-core/src/main/java/org/apache/shardingsphere/transaction/spi/TransactionConfigurationFileGenerator.java
> +     * @param originTransactionProps transaction rule props
The description of param `originTransactionProps  ` seems to not match very much

2022-02-23 04:56 UTC, terrymanu requested changes

2022-02-23 04:56 UTC, terrymanu commented on shardingsphere-kernel/shardingsphere-transaction/shardingsphere-transaction-core/src/main/java/org/apache/shardingsphere/transaction/spi/TransactionConfigurationFileGenerator.java
>       * @return transaction rule props
The java doc is `Get transaction configuration`, but the return value is `transaction rule props`, please unify them

2022-02-23 04:56 UTC, terrymanu commented on shardingsphere-kernel/shardingsphere-transaction/shardingsphere-transaction-core/src/main/java/org/apache/shardingsphere/transaction/spi/TransactionConfigurationFileGenerator.java
> +    Optional<Properties> getTransactionProps(Properties originTransactionProps, Optional<SchemaConfiguration> schemaConfiguration, String modeType);
Input param cannot permit optional value, please follow IDEA's warning to adjust it.

2022-02-23 04:56 UTC, terrymanu commented on shardingsphere-kernel/shardingsphere-transaction/shardingsphere-transaction-type/shardingsphere-transaction-xa/shardingsphere-transaction-xa-provider/shardingsphere-transaction-xa-narayana/src/main/java/org/apache/shardingsphere/transaction/xa/narayana/config/NarayanaConfigurationFileGenerator.java
> +        if (null != transactionRule.getProps() && !transactionRule.getProps().isEmpty()) {
When `transactionRule.getProps()` is null?

2022-02-23 04:56 UTC, terrymanu commented on shardingsphere-kernel/shardingsphere-transaction/shardingsphere-transaction-type/shardingsphere-transaction-xa/shardingsphere-transaction-xa-provider/shardingsphere-transaction-xa-narayana/src/main/java/org/apache/shardingsphere/transaction/xa/narayana/config/NarayanaConfigurationFileGenerator.java
> +        } else if ("Cluster".equalsIgnoreCase(modeType) && schemaConfiguration.isPresent()) {
`equalsIgnoreCase` or just `equals`? Does other codes use `equalsIgnoreCase` to judge mode type?

2022-02-23 04:56 UTC, terrymanu commented on shardingsphere-kernel/shardingsphere-transaction/shardingsphere-transaction-core/src/main/java/org/apache/shardingsphere/transaction/spi/TransactionConfigurationFileGenerator.java
> +    Optional<Properties> getTransactionProps(Properties originTransactionProps, Optional<SchemaConfiguration> schemaConfiguration, String modeType);
How about replace `Optional<Properties>` to empty Properties if no contents?

2022-02-23 07:24 UTC, terrymanu approved these changes

2022-02-23 07:25 UTC, merged