support auto rollback when report exception in transaction block.
apache/shardingsphere pull request #15779
Opened 2022-03-03 10:50 UTC by jingshanglu

[design detail](https://u01f1kqxrl.feishu.cn/docs/doccntaO4s7K5I5FbML5UAponJe#)

Changes proposed in this pull request:
- support auto rollback when report exception in transaction block for postgresql and opengauss

2022-03-06 14:56 UTC, terrymanu commented
> [design detail](https://u01f1kqxrl.feishu.cn/docs/doccntaO4s7K5I5FbML5UAponJe#)
> 
> Changes proposed in this pull request:
> 
> * support auto rollback when report exception in transaction block for postgresql and opengauss

@jingshanglu Hi, could you give the English version on GitHub?

2022-03-06 15:03 UTC, terrymanu requested changes

2022-03-06 15:03 UTC, terrymanu commented on shardingsphere-proxy/shardingsphere-proxy-frontend/shardingsphere-proxy-frontend-core/src/main/java/org/apache/shardingsphere/proxy/frontend/command/CommandExecutorTask.java
> +        }
Please use SPI

2022-03-06 15:03 UTC, terrymanu commented on shardingsphere-kernel/shardingsphere-transaction/shardingsphere-transaction-core/src/main/java/org/apache/shardingsphere/transaction/spi/ShardingSphereTransactionManager.java
>      void commit();
Is `commit` still useful?

2022-03-07 03:36 UTC, jingshanglu commented
> > [design detail](https://u01f1kqxrl.feishu.cn/docs/doccntaO4s7K5I5FbML5UAponJe#)
> > Changes proposed in this pull request:
> > 
> > * support auto rollback when report exception in transaction block for postgresql and opengauss
> 
> @jingshanglu Hi, could you give the English version on GitHub?

ok

2022-03-07 06:45 UTC, jingshanglu commented on shardingsphere-kernel/shardingsphere-transaction/shardingsphere-transaction-core/src/main/java/org/apache/shardingsphere/transaction/spi/ShardingSphereTransactionManager.java
>      void commit();
sharding-jdbc use it.

2022-03-08 13:14 UTC, terrymanu approved these changes

2022-03-08 13:15 UTC, merged