Add mode to parser to support $$ in pg
apache/shardingsphere pull request #15852
Opened 2022-03-07 10:58 UTC by tuichenchuxin

Fixes #15835.

Changes proposed in this pull request:
- add Add mode to parser to support $$ in pg
- add test case

2022-03-07 12:01 UTC, strongduanmu requested changes

2022-03-07 12:01 UTC, strongduanmu commented on shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-postgresql/src/main/antlr4/imports/postgresql/ModeLexer.g4
> +BeginDollarStringConstant
@tuichenchuxin Please rename it with BEGIN_DOLLAR_STRING_CONSTANT.

2022-03-07 12:01 UTC, strongduanmu commented on shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-postgresql/src/main/java/org/apache/shardingsphere/sql/parser/postgresql/parser/PostgreSQLLexerBase.java
> +public abstract class PostgreSQLLexerBase extends Lexer {
Add javadoc for PostgreSQLLexerBase.

2022-03-08 02:13 UTC, tuichenchuxin commented on shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-postgresql/src/main/java/org/apache/shardingsphere/sql/parser/postgresql/parser/PostgreSQLLexerBase.java
> +public abstract class PostgreSQLLexerBase extends Lexer {
Thanks. Done.

2022-03-08 02:14 UTC, tuichenchuxin commented on shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-postgresql/src/main/antlr4/imports/postgresql/ModeLexer.g4
> +
Thanks. Done.

2022-03-08 03:06 UTC, strongduanmu approved these changes

2022-03-08 03:06 UTC, merged