support set blank to clear plain after encrypt
apache/shardingsphere pull request #15965
Opened 2022-03-10 07:32 UTC by cheese8

Ref #12957.

SS already support set to null to clear the plain, here is set to blank

Changes proposed in this pull request:
-support set blank to clear plain after encrypt

2022-04-01 03:03 UTC, TeslaCN commented
Hi @strongduanmu 
Could you take a look at this?

2022-04-01 03:15 UTC, strongduanmu commented
> #12957

@TeslaCN This PR needs more discussion, so it will be better for the next release.

2022-04-16 12:20 UTC, strongduanmu requested changes

2022-04-16 12:20 UTC, strongduanmu commented on shardingsphere-infra/shardingsphere-infra-common/src/main/java/org/apache/shardingsphere/infra/hint/SQLHintExtractor.java
> +        return sqlHintProperties.getValue(SQLHintPropertiesKey.NO_ENCRYPT_REWRITE_KEY);
@cheese8 Can you rename NO_ENCRYPT_REWRITE_KEY to SKIP_ENCRYPT_REWRITE_KEY?

2022-04-16 12:20 UTC, strongduanmu commented on shardingsphere-infra/shardingsphere-infra-common/src/main/java/org/apache/shardingsphere/infra/hint/SQLHintPropertiesKey.java
> +    NO_ENCRYPT_REWRITE_KEY("noEncryptRewrite", String.valueOf(Boolean.FALSE), boolean.class);
@cheese8 Can you rename noEncryptRewrite to skipEncryptRewrite?

2022-04-16 12:20 UTC, strongduanmu commented on shardingsphere-test/shardingsphere-rewrite-test/src/test/resources/scenario/encrypt/case/query-with-cipher/dml/update/update.xml
> -
Please keep same indent with previous line.

2022-04-16 12:20 UTC, strongduanmu commented on shardingsphere-test/shardingsphere-rewrite-test/src/test/resources/scenario/encrypt/case/query-with-cipher/dml/update/update.xml
> -
Please keep same indent with previous line.

2022-04-16 13:01 UTC, cheese8 commented on shardingsphere-test/shardingsphere-rewrite-test/src/test/resources/scenario/encrypt/case/query-with-cipher/dml/update/update.xml
> -
ok

2022-04-16 23:40 UTC, strongduanmu approved these changes

2022-04-16 23:40 UTC, merged