Add unit test for EncryptOrderByItemTokenGenerator
apache/shardingsphere pull request #16012
Opened 2022-03-11 15:33 UTC by Trydamere

Fixes #15822.

Changes proposed in this pull request:
- add unit test for the generateSQLTokens method in EncryptOrderByItemTokenGenerator.

2022-03-12 00:29 UTC, strongduanmu commented on shardingsphere-features/shardingsphere-encrypt/shardingsphere-encrypt-core/src/test/java/org/apache/shardingsphere/encrypt/rewrite/impl/EncryptOrderByItemTokenGeneratorTest.java
> +
Hi @Trydamere, can you remove this useless blank line?

2022-03-12 08:35 UTC, strongduanmu requested changes
Hi @Trydamere, can you sync latest master branch to solve ci error?

2022-03-12 09:38 UTC, Trydamere commented
I will do it.

2022-03-13 04:08 UTC, strongduanmu approved these changes
@Trydamere Thank you.

2022-03-13 04:09 UTC, merged