support parsing Postgre sql DROP OWNED
apache/shardingsphere pull request #16178
Opened 2022-03-18 06:41 UTC by Trydamere

Fixes #ISSUSE_ID.

Changes proposed in this pull request:
- support parsing Postgre sql DROP OWNED
- add a new corresponding SQL case in [SQL Cases](https://github.com/apache/shardingsphere/tree/master/shardingsphere-test/shardingsphere-parser-test/src/main/resources/sql/supported?rgh-link-date=2022-03-02T05%3A57%3A34Z) and expected parsed result in [Expected Statment XML](https://github.com/apache/shardingsphere/tree/master/shardingsphere-test/shardingsphere-parser-test/src/main/resources/case?rgh-link-date=2022-03-02T05%3A57%3A34Z).
- Run [SQLParserParameterizedTest](https://github.com/apache/shardingsphere/blob/master/shardingsphere-test/shardingsphere-parser-test/src/main/java/org/apache/shardingsphere/test/sql/parser/parameterized/engine/SQLParserParameterizedTest.java?rgh-link-date=2022-03-02T05%3A57%3A34Z) and [UnsupportedSQLParserParameterizedTest](https://github.com/apache/shardingsphere/blob/master/shardingsphere-test/shardingsphere-parser-test/src/main/java/org/apache/shardingsphere/test/sql/parser/parameterized/engine/UnsupportedSQLParserParameterizedTest.java?rgh-link-date=2022-03-02T05%3A57%3A34Z) to make sure no exceptions.

2022-03-18 13:03 UTC, ThanoshanMV commented
Hi @Trydamere, can you please fix the CI error?

2022-03-18 13:27 UTC, Trydamere commented
Sure.

2022-03-18 13:43 UTC, ThanoshanMV commented
@Trydamere, we need to fix the checkstyle violation: `Error:  src/main/java/org/apache/shardingsphere/sql/parser/sql/common/statement/ddl/DropOwnedStatement.java:[27,94] (whitespace) WhitespaceAround: '{' is not preceded with whitespace.` After fixing the changes please execute the command `mvn clean install -Prelease` to ensure the build is passed successfully.

2022-03-18 13:47 UTC, ThanoshanMV commented on shardingsphere-sql-parser/shardingsphere-sql-parser-statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/dialect/statement/postgresql/ddl/PostgreSQLDropOwnedStatement.java
> +public class PostgreSQLDropOwnedStatement extends DropOwnedStatement implements PostgreSQLStatement {
Please add `final` here.

2022-03-18 14:18 UTC, Trydamere commented
Working on it.

2022-03-19 02:42 UTC, ThanoshanMV submitted a review, later dismissed

2022-03-20 03:36 UTC, strongduanmu requested changes
Hi @Trydamere, can you solve code conflict?

2022-03-20 03:51 UTC, Trydamere commented
Sure.

2022-03-20 07:08 UTC, strongduanmu approved these changes
@Trydamere Good job, merged. And thanks @ThanoshanMV for review.

2022-03-20 07:08 UTC, merged