test file added for Sharding Insert Values Token
apache/shardingsphere pull request #16202
Opened 2022-03-19 02:11 UTC by shreya024

Fixes #16100 .

2022-03-19 02:42 UTC, shreya024 commented
CI is failing because of error in shardingsphere-pipeline-test

2022-03-19 03:36 UTC, strongduanmu requested changes

2022-03-19 03:36 UTC, strongduanmu commented on shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-core/src/test/java/org/apache/shardingsphere/sharding/rewrite/token/pojo/ShardingInsertValuesTokenTest.java
> +        final RouteMapper routeMapper = new RouteMapper("logic_ds", "actual_ds");
@shreya024 Please remove final for params in method scope.

2022-03-19 03:36 UTC, strongduanmu commented on shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-core/src/test/java/org/apache/shardingsphere/sharding/rewrite/token/pojo/ShardingInsertValuesTokenTest.java
> +        List<ExpressionSegment> expressionSegment = new ArrayList<>(2);
`new LinkedList<>();` may be better.

2022-03-20 00:36 UTC, strongduanmu approved these changes
@shreya024 Thank you.

2022-03-20 00:36 UTC, merged