Add unit test for EncryptInsertOnUpdateTokenGenerator
apache/shardingsphere pull request #17674
Opened 2022-05-15 13:13 UTC by iisheng

For #15820 .

Changes proposed in this pull request:
- Add unit test for EncryptInsertOnUpdateTokenGenerator#isGenerateSQLToken
- Add unit test for EncryptInsertOnUpdateTokenGenerator#generateSQLTokens

2022-05-16 16:09 UTC, terrymanu reviewed
Please fix the CI

2022-05-17 12:51 UTC, iisheng commented
> Please fix the CI



>

2022-05-17 15:26 UTC, terrymanu requested changes

2022-05-17 15:26 UTC, terrymanu commented on shardingsphere-features/shardingsphere-encrypt/shardingsphere-encrypt-core/src/test/java/org/apache/shardingsphere/encrypt/rewrite/token/EncryptInsertOnUpdateTokenGeneratorTest.java
> +public class EncryptInsertOnUpdateTokenGeneratorTest {
Please add final if class does not design for extension

2022-05-17 15:26 UTC, terrymanu commented on shardingsphere-features/shardingsphere-encrypt/shardingsphere-encrypt-core/src/test/java/org/apache/shardingsphere/encrypt/rewrite/token/EncryptInsertOnUpdateTokenGeneratorTest.java
> +    }
Please move the method after method with the first call

2022-05-17 16:07 UTC, merged