Fix autocommit
apache/shardingsphere pull request #17904
Opened 2022-05-24 08:04 UTC by jingshanglu

Fixes #16894 .

Changes proposed in this pull request:
- When `autocommit=0`, transactions will be automatically started only when SQL is not a `TCLStatement`

### Test

- [x] Manual

2022-05-24 09:29 UTC, strongduanmu requested changes

2022-05-24 09:48 UTC, jingshanglu commented on shardingsphere-proxy/shardingsphere-proxy-backend/src/main/java/org/apache/shardingsphere/proxy/backend/communication/jdbc/connection/JDBCBackendConnection.java
> +    public Void prepareForTaskExecution() throws SQLException {
I don't think it's necessary to use `BackendConnectionException` to wrap all of them. It's necessary to handle `BackendConnectionException ` where other calls are caused. In fact, it's `SQLException`.

2022-05-24 09:49 UTC, jingshanglu commented on shardingsphere-proxy/shardingsphere-proxy-backend/src/main/java/org/apache/shardingsphere/proxy/backend/communication/jdbc/connection/JDBCBackendConnection.java
> +    public Void prepareForTaskExecution() throws SQLException {
@TeslaCN PTAL

2022-05-24 11:42 UTC, TeslaCN commented on shardingsphere-proxy/shardingsphere-proxy-backend/src/main/java/org/apache/shardingsphere/proxy/backend/communication/jdbc/connection/JDBCBackendConnection.java
> +    public Void prepareForTaskExecution() throws SQLException {
`BackendConnectionException` is used for decoupling codes from JDBC.

2022-05-24 11:45 UTC, TeslaCN commented on shardingsphere-proxy/shardingsphere-proxy-backend/src/main/java/org/apache/shardingsphere/proxy/backend/communication/jdbc/connection/JDBCBackendConnection.java
> +    public Void prepareForTaskExecution() throws SQLException {
But the current progress of Vert.x driver is pending. We can merge this PR for now.

2022-05-25 00:42 UTC, strongduanmu commented on shardingsphere-proxy/shardingsphere-proxy-backend/src/main/java/org/apache/shardingsphere/proxy/backend/communication/jdbc/connection/JDBCBackendConnection.java
> +    public Void prepareForTaskExecution() throws SQLException {
> But the current progress of Vert.x driver is pending. We can merge this PR for now.

Thank you.

2022-05-25 00:42 UTC, strongduanmu approved these changes

2022-05-25 00:42 UTC, merged