parse aggregationProjectionSegment with columnSegment
apache/shardingsphere pull request #18045
Opened 2022-05-29 07:23 UTC by cheese8

For #17987.

Changes proposed in this pull request:
- parse aggregationProjectionSegment with columnSegment

2022-05-29 09:13 UTC, strongduanmu requested changes
Hi @cheese8, can you describe the problem with parse in original issue?

2022-05-29 12:42 UTC, cheese8 commented
> Hi @cheese8, can you describe the problem with parse in original issue?

Yes, while the **expr** is in table.column format, the parser did not support for now. This PR is plan to support this sutiation.

2022-05-30 03:50 UTC, tuichenchuxin commented
I think expr has contains columRef. Maybe we should found why this is not parsed to column.

2022-05-30 03:51 UTC, tuichenchuxin requested changes
I think expr has contains columRef. Maybe we should found why this is not parsed to column.

2022-05-30 07:25 UTC, tuichenchuxin requested changes

2022-05-30 07:25 UTC, tuichenchuxin commented on shardingsphere-sql-parser/shardingsphere-sql-parser-statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/segment/dml/item/AggregationProjectionSegment.java
> +    private ExpressionSegment expression;
maybe have multi expression.
```
private final Collection<ExpressionSegment> parameters = new LinkedList<>();
```
This maybe better.

2022-05-30 13:06 UTC, tuichenchuxin requested changes

2022-05-30 13:06 UTC, tuichenchuxin commented on shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/impl/MySQLStatementSQLVisitor.java
> +            if (visitNode instanceof ColumnSegment) {
visit exprContext is always expressionSegment, So there is no need to cast to ColumnSegment or others.

2022-05-31 01:15 UTC, tuichenchuxin requested changes

2022-05-31 01:15 UTC, tuichenchuxin commented on shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/impl/MySQLStatementSQLVisitor.java
> +            if (visitNode instanceof ColumnSegment) {
There is no need to judge instance of. Can cast to expressionSegment directly, and add to list.

2022-05-31 01:41 UTC, tuichenchuxin requested changes

2022-05-31 01:41 UTC, tuichenchuxin commented on shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-postgresql/src/main/java/org/apache/shardingsphere/sql/parser/postgresql/visitor/statement/impl/PostgreSQLStatementSQLVisitor.java
> +        return Collections.singletonList((ExpressionSegment) visit(ctx.funcArgList()));
argList could return multi expressionSegments. We should implement visitArgList method.

2022-05-31 01:41 UTC, tuichenchuxin commented on shardingsphere-test/shardingsphere-parser-test/src/main/resources/case/dml/select-aggregate.xml
> +            <aggregation-projection type="SUM" inner-expression="(t_order.user_id)" alias="user_id_sum" start-index="7" stop-index="26" />
Maybe we need to extract params and judge.

2022-05-31 05:38 UTC, tuichenchuxin commented on shardingsphere-test/shardingsphere-parser-test/src/main/resources/case/dml/select-aggregate.xml
> +                        <owner name="t_order" start-index="8" stop-index="16"/>
This test need to add parameter in ExpectedAggregationProjection.java

2022-06-01 01:32 UTC, tuichenchuxin approved these changes

2022-06-01 03:36 UTC, strongduanmu approved these changes
@cheese8 Good job, merge.

2022-06-01 03:36 UTC, merged