Fix begin for postgresql & opengauss
apache/shardingsphere pull request #18359
Opened 2022-06-14 10:05 UTC by jingshanglu

2022-06-15 07:57 UTC, terrymanu requested changes

2022-06-15 07:57 UTC, terrymanu commented on shardingsphere-proxy/shardingsphere-proxy-backend/src/main/java/org/apache/shardingsphere/proxy/backend/exception/InTransactionException.java
> +public final class InTransactionException extends BackendException {
Please use @RequiredArgsConstructor

2022-06-15 07:57 UTC, terrymanu commented on shardingsphere-proxy/shardingsphere-proxy-frontend/shardingsphere-proxy-frontend-core/src/main/java/org/apache/shardingsphere/proxy/frontend/command/CommandExecutorTask.java
> +            databaseProtocolFrontendEngine.handleException(connectionSession, ex);
It is better to use `|` for multiple exception process

2022-06-16 05:59 UTC, tristaZero approved these changes

2022-06-16 05:59 UTC, terrymanu approved these changes

2022-06-16 06:00 UTC, merged