Feature
apache/shardingsphere pull request #18375
Opened 2022-06-15 09:00 UTC by azexcy

Fixes #18075.

Changes proposed in this pull request:
- Improve decode method, not consume incomplete data
- skip checksum, not change the source ByteBuf.
- Improve unit test

2022-06-15 10:19 UTC, menghaoranss commented
@azexcy please modify the title to describe what this PR does

2022-06-15 10:34 UTC, azexcy commented
> @azexcy please modify the title to describe what this PR does

changed

2022-06-15 13:26 UTC, sandynz requested changes
Thanks. The decoding process is much improved.

2022-06-15 13:26 UTC, sandynz commented on shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-dialect/shardingsphere-data-pipeline-mysql/src/main/java/org/apache/shardingsphere/data/pipeline/mysql/ingest/client/netty/MySQLBinlogEventPacketDecoder.java
> +        // readable bytes must grete + seqId(1b) + statusCode(1b) + header-length(19b) +
`grete` means greater than?

2022-06-15 13:26 UTC, sandynz commented on shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-dialect/shardingsphere-data-pipeline-mysql/src/main/java/org/apache/shardingsphere/data/pipeline/mysql/ingest/client/netty/MySQLBinlogEventPacketDecoder.java
> +            }
Seems PlaceholderEvent is instance of AbstractBinlogEvent, could it be improved?

2022-06-16 02:04 UTC, sandynz commented on shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-dialect/shardingsphere-data-pipeline-mysql/src/main/java/org/apache/shardingsphere/data/pipeline/mysql/ingest/client/netty/MySQLBinlogEventPacketDecoder.java
> +            }
PlaceholderEvent should be kept.

2022-06-16 02:05 UTC, sandynz commented on shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-dialect/shardingsphere-data-pipeline-mysql/src/main/java/org/apache/shardingsphere/data/pipeline/mysql/ingest/client/netty/MySQLBinlogEventPacketDecoder.java
> +                return decodeTableMapEvent(binlogEventHeader, payload);
For ROTATE_EVENT etc, keep the original logic, just return null etc.

2022-06-16 03:31 UTC, sandynz requested changes

2022-06-16 03:31 UTC, sandynz commented on shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-dialect/shardingsphere-data-pipeline-mysql/src/main/java/org/apache/shardingsphere/data/pipeline/mysql/ingest/client/netty/MySQLBinlogEventPacketDecoder.java
>      }
Could we keep decodeRotateEvent and decodeTableMapEvent return void? Since it's not necessary to return result.

2022-06-16 05:37 UTC, sandynz approved these changes

2022-06-16 05:40 UTC, merged