Add query route primary data source when replica all offline.
apache/shardingsphere pull request #18473
Opened 2022-06-21 03:12 UTC by zjcnb

Fixes #18441

2022-06-21 09:07 UTC, tristaZero requested changes
How about `write-data-source-query-enable`?

2022-06-21 10:21 UTC, zjcnb commented
> write-data-source-query-enable

Yeah, it 's better.

2022-06-22 05:48 UTC, menghaoranss commented on shardingsphere-features/shardingsphere-readwrite-splitting/shardingsphere-readwrite-splitting-core/src/main/java/org/apache/shardingsphere/readwritesplitting/route/impl/ReadwriteSplittingDataSourceRouter.java
> +    private boolean isAllowWriteDatasourceQuery() {
Datasource should be DataSource

2022-06-22 06:02 UTC, tristaZero approved these changes

2022-06-22 06:03 UTC, tristaZero requested changes
test

2022-06-22 06:04 UTC, tristaZero requested changes
test

2022-06-22 06:44 UTC, tristaZero approved these changes

2022-06-22 06:44 UTC, merged