listen on specified addresses
apache/shardingsphere pull request #18893
Opened 2022-07-06 08:09 UTC by csonezp

Fixes #18554 .

To be compatible with both ways, I modified the start script and gave default values for port and conf path .
If the user does not set port or conf path, they will be set to -1/${DEPLOY_DIR}/conf.
The default value for port is -1, that mean user did not specify a port, and it will return Optional.empty() when getPort.

@TeslaCN is this solution correct? can you give me some suggestions to improve the code quality? Thanks!

Changes proposed in this pull request:
- support listen on specified addresses

2022-07-06 09:00 UTC, TeslaCN commented on shardingsphere-distribution/shardingsphere-proxy-distribution/src/main/resources/bin/start.sh
> +    echo "start.sh [-h addresses] [-p port] [-c /path/to/conf]"
We have already changed the `-h`.

2022-07-06 09:03 UTC, csonezp commented on shardingsphere-distribution/shardingsphere-proxy-distribution/src/main/resources/bin/start.sh
> +    echo "start.sh [-h addresses] [-p port] [-c /path/to/conf]"
> We have already changed the `-h`.

done

2022-07-07 08:48 UTC, TeslaCN requested changes
Hi @csonezp 
I tried your branch and I found a problem:

I wrote an absolute path of config directory:
```bash
bin/start.sh 33306 /home/wuweijie/dev/shardingsphere/proxy/master/mysql/conf
```

But the absolute path was prefixed with `DEPLOY_DIR`
```
$ tail logs/stdout.log                                                                                                                                                                                                                                                                                             [16:44:09]
        at org.apache.shardingsphere.proxy.backend.config.ProxyConfigurationLoader.load(ProxyConfigurationLoader.java:60)
        at org.apache.shardingsphere.proxy.Bootstrap.main(Bootstrap.java:49)
Exception in thread "main" java.io.FileNotFoundException: /home/wuweijie/projects/shardingsphere/shardingsphere-distribution/shardingsphere-proxy-distribution/target/apache-shardingsphere-5.1.3-SNAPSHOT-shardingsphere-proxy-bin/home/wuweijie/dev/shardingsphere/proxy/master/mysql/conf/server.yaml (No such file or directory)
        at java.base/java.io.FileInputStream.open0(Native Method)
        at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
        at org.apache.shardingsphere.infra.yaml.engine.YamlEngine.unmarshal(YamlEngine.java:54)
        at org.apache.shardingsphere.proxy.backend.config.ProxyConfigurationLoader.loadServerConfiguration(ProxyConfigurationLoader.java:74)
        at org.apache.shardingsphere.proxy.backend.config.ProxyConfigurationLoader.load(ProxyConfigurationLoader.java:60)
        at org.apache.shardingsphere.proxy.Bootstrap.main(Bootstrap.java:49)
```

2022-07-07 11:32 UTC, csonezp commented
> Hi @csonezp I tried your branch and I found a problem:
> 
> I wrote an absolute path of config directory:
> 
> ```shell
> bin/start.sh 33306 /home/wuweijie/dev/shardingsphere/proxy/master/mysql/conf
> ```
> 
> But the absolute path was prefixed with `DEPLOY_DIR`
> 
> ```
> $ tail logs/stdout.log                                                                                                                                                                                                                                                                                             [16:44:09]
>         at org.apache.shardingsphere.proxy.backend.config.ProxyConfigurationLoader.load(ProxyConfigurationLoader.java:60)
>         at org.apache.shardingsphere.proxy.Bootstrap.main(Bootstrap.java:49)
> Exception in thread "main" java.io.FileNotFoundException: /home/wuweijie/projects/shardingsphere/shardingsphere-distribution/shardingsphere-proxy-distribution/target/apache-shardingsphere-5.1.3-SNAPSHOT-shardingsphere-proxy-bin/home/wuweijie/dev/shardingsphere/proxy/master/mysql/conf/server.yaml (No such file or directory)
>         at java.base/java.io.FileInputStream.open0(Native Method)
>         at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
>         at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
>         at org.apache.shardingsphere.infra.yaml.engine.YamlEngine.unmarshal(YamlEngine.java:54)
>         at org.apache.shardingsphere.proxy.backend.config.ProxyConfigurationLoader.loadServerConfiguration(ProxyConfigurationLoader.java:74)
>         at org.apache.shardingsphere.proxy.backend.config.ProxyConfigurationLoader.load(ProxyConfigurationLoader.java:60)
>         at org.apache.shardingsphere.proxy.Bootstrap.main(Bootstrap.java:49)
> ```

@TeslaCN my bad, I will go through the script and write a test report. Is there a way to test the script file in the source code?

And I found a bug in master branch: if user wrote an absolute path, the script  will merge  the absolute path and ${DEPLOY_DIR},  and then add the result to ${CLASS_PATH}. Like this:
![image](https://user-images.githubusercontent.com/3190994/177762773-1bbfd115-68bb-428a-b6b3-818fa817e392.png)
should i fix it?

2022-07-08 01:07 UTC, TeslaCN commented
You could fix it if you like.

2022-07-08 10:10 UTC, csonezp commented
@TeslaCN

2022-07-09 03:14 UTC, TeslaCN approved these changes
Hi @csonezp
Thank you.

2022-07-09 03:15 UTC, merged

2022-07-10 13:49 UTC, tristaZero commented
Hello @csonezp Thanks for this nice feature, which will be included in the next release, look forward!
@TeslaCN Patient review!