make CONNECTION_ID() support alias
apache/shardingsphere pull request #19110
Opened 2022-07-13 12:09 UTC by csonezp

Fixes #17949 

Changes proposed in this pull request:
- make CONNECTION_ID() support alias

2022-07-13 14:51 UTC, terrymanu requested changes

2022-07-13 14:51 UTC, terrymanu commented on shardingsphere-proxy/shardingsphere-proxy-backend/src/test/java/org/apache/shardingsphere/proxy/backend/text/admin/mysql/executor/ShowConnectionIdExecutorTest.java
> +
Please remove useless blank line

2022-07-13 14:51 UTC, terrymanu commented on shardingsphere-proxy/shardingsphere-proxy-backend/src/test/java/org/apache/shardingsphere/proxy/backend/text/admin/mysql/executor/ShowConnectionIdExecutorTest.java
> +
Please remove useless blank line

2022-07-13 14:51 UTC, terrymanu commented on shardingsphere-proxy/shardingsphere-proxy-backend/src/test/java/org/apache/shardingsphere/proxy/backend/text/admin/mysql/executor/ShowConnectionIdExecutorTest.java
> +
Please remove useless blank line

2022-07-13 14:51 UTC, terrymanu commented on shardingsphere-proxy/shardingsphere-proxy-backend/src/test/java/org/apache/shardingsphere/proxy/backend/text/admin/mysql/executor/ShowConnectionIdExecutorTest.java
> +        return statement;
return value should name as `result`

2022-07-13 14:51 UTC, terrymanu commented on shardingsphere-proxy/shardingsphere-proxy-backend/src/test/java/org/apache/shardingsphere/proxy/backend/text/admin/mysql/executor/ShowConnectionIdExecutorTest.java
> +        return statement;
return value should name as `result`

2022-07-14 02:40 UTC, csonezp commented
@terrymanu done

2022-07-14 03:36 UTC, terrymanu approved these changes

2022-07-14 03:36 UTC, merged