Add postgresql data source check at scaling
apache/shardingsphere pull request #19356
Opened 2022-07-19 08:39 UTC by azexcy

Fixes #ISSUSE_ID.

Changes proposed in this pull request:
- Add check

2022-07-19 11:47 UTC, azexcy commented
Checks only if user is super role or have replication privilege, no check create table or schema, because create table or schema privilege verified before

2022-07-20 02:51 UTC, sandynz requested changes
Thanks. Some privileges check snippets could be double checked.

2022-07-20 02:51 UTC, sandynz commented on shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-dialect/shardingsphere-data-pipeline-postgresql/src/main/java/org/apache/shardingsphere/data/pipeline/postgresql/check/datasource/PostgreSQLDataSourceChecker.java
> +                }
Could we not limit role to super role?
If user create a role and grant replication privilege, it should work.

2022-07-20 02:51 UTC, sandynz commented on shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-dialect/shardingsphere-data-pipeline-postgresql/src/main/java/org/apache/shardingsphere/data/pipeline/postgresql/check/datasource/PostgreSQLDataSourceChecker.java
> +            PreparedStatement preparedStatement = connection.prepareStatement(SHOW_GRANTS_SQL);
It's better to put `connection.prepareStatement` in try-resource.

2022-07-20 02:51 UTC, sandynz commented on shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-dialect/shardingsphere-data-pipeline-postgresql/src/main/java/org/apache/shardingsphere/data/pipeline/postgresql/check/datasource/PostgreSQLDataSourceChecker.java
> +                String isReplicationRole = resultSet.getString(REPLICATION_ROLE_NAME);
If ResultSet of SHOW_GRANTS_SQL has no result, `resultSet.next()` might return false, could we just run `resultSet.getString`?

2022-07-20 03:07 UTC, sandynz commented on shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-dialect/shardingsphere-data-pipeline-postgresql/src/main/java/org/apache/shardingsphere/data/pipeline/postgresql/check/datasource/PostgreSQLDataSourceChecker.java
> +                }
By mistake, `SELECT * FROM pg_roles WHERE rolname = ?` 's parameter is current login user.

2022-07-20 03:09 UTC, sandynz commented
Refer to https://www.postgresql.org/docs/current/sql-createuser.html

> CREATE USER is now an alias for [CREATE ROLE](https://www.postgresql.org/docs/current/sql-createrole.html). The only difference is that when the command is spelled CREATE USER, LOGIN is assumed by default, whereas NOLOGIN is assumed when the command is spelled CREATE ROLE.

2022-07-20 03:32 UTC, azexcy commented
Refer to https://www.postgresql.org/docs/current/sql-createrole.html
> The INHERIT attribute governs inheritance of grantable privileges (that is, access privileges for database objects and role memberships). It does not apply to the special role attributes set by CREATE ROLE and ALTER ROLE. For example, being a member of a role with CREATEDB privilege does not immediately grant the ability to create databases, even if INHERIT is set; it would be necessary to become that role via [SET ROLE](https://www.postgresql.org/docs/current/sql-set-role.html) before creating a database.

2022-07-20 03:38 UTC, sandynz commented on shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-dialect/shardingsphere-data-pipeline-postgresql/src/main/java/org/apache/shardingsphere/data/pipeline/postgresql/check/datasource/PostgreSQLDataSourceChecker.java
> +                }
Is it possible to supply suggestion of how to add REPLICATION privilege?

2022-07-20 06:07 UTC, sandynz requested changes

2022-07-20 06:07 UTC, sandynz commented on shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-dialect/shardingsphere-data-pipeline-postgresql/src/main/java/org/apache/shardingsphere/data/pipeline/postgresql/check/datasource/PostgreSQLDataSourceChecker.java
> +    private static final String REPLICATION_ROLE_NAME = "rolreplication";
Could we just inline these string? It's short enough and just used one time.

Or could we change it to xxx_COLUMN_NAME? It's not ROLE NAME.

2022-07-20 06:07 UTC, sandynz commented on shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-dialect/shardingsphere-data-pipeline-postgresql/src/main/java/org/apache/shardingsphere/data/pipeline/postgresql/check/datasource/PostgreSQLDataSourceChecker.java
> +                            metaData.getUserName()));
`sql example is` could be `you could try`

2022-07-20 13:24 UTC, merged