fix PostgreSQL/openGauss RESET statement
apache/shardingsphere pull request #19900
Opened 2022-08-05 08:47 UTC by runqi-zhao

Fixes #19810.

Changes proposed in this pull request:
- According to the discussion, only one EOF needs to be removed

2022-08-06 08:42 UTC, strongduanmu requested changes

2022-08-06 08:42 UTC, strongduanmu commented on shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-postgresql/src/main/antlr4/imports/postgresql/DALStatement.g4
> +    : RESET (ALL | identifier)
@runqi-zhao Can you add some sql parse test case?

2022-08-06 16:02 UTC, runqi-zhao commented
Hi @strongduanmu, After carefully studying the syntax of reset and looking at it, I found that the corresponding test cases have all been implemented, what is the specific use case that you need to add here?

2022-08-07 01:30 UTC, strongduanmu approved these changes

2022-08-07 01:30 UTC, merged

2022-08-07 01:31 UTC, strongduanmu commented
> Hi @strongduanmu, After carefully studying the syntax of reset and looking at it, I found that the corresponding test cases have all been implemented, what is the specific use case that you need to add here?

@runqi-zhao If there are already test cases, then there is no need to add additional test cases.