add audit document
apache/shardingsphere pull request #21029
Opened 2022-09-17 01:19 UTC by dongzl

ref #18430 .

Changes proposed in this pull request:
  - add audit document.

---

Before committing this PR, I'm sure that I have checked the following options:
- [x] My code follows the [code of conduct](https://shardingsphere.apache.org/community/en/involved/conduct/code/) of this project.
- [x] I have self-reviewed the commit code.
- [x] I have triggered maven check: `mvn clean install -B -T2C -DskipTests -Dmaven.javadoc.skip=true -e`.
- [x] I have made corresponding changes to the documentation.
- [x] I have added corresponding unit tests for my changes.

2022-09-17 16:28 UTC, terrymanu requested changes

2022-09-17 16:28 UTC, terrymanu commented on docs/document/content/user-manual/common-config/builtin-algorithm/audit.en.md
> +title = "Key Generate Algorithm"
It should be `Sharding Audit Algorithm`

2022-09-18 07:51 UTC, dongzl commented on docs/document/content/user-manual/common-config/builtin-algorithm/audit.en.md
> +title = "Key Generate Algorithm"
> It should be `Sharding Audit Algorithm`

Thanks, done.

2022-09-19 10:25 UTC, strongduanmu approved these changes

2022-09-19 10:27 UTC, strongduanmu commented
LGTM, let's wait @terrymanu review this pr again.

2022-09-25 12:09 UTC, terrymanu approved these changes

2022-09-25 12:09 UTC, merged