Support sharding SQL hint.
apache/shardingsphere pull request #21346
Opened 2022-10-05 09:56 UTC by dongzl

ref #20736 .

Changes proposed in this pull request:
- support sharding sql hint.
- add test case.

2022-10-05 14:03 UTC, tuichenchuxin reviewed
I think SQL hint is same as HintManager, the only difference between them is just setting or getting the value way is different.

2022-10-09 02:03 UTC, tuichenchuxin reviewed
LGTM. By the way, why databaseValue is only int? It should be comparable is ok.

2022-10-09 11:57 UTC, dongzl commented
> LGTM. By the way, why databaseValue is only int? It should be comparable is ok.

OK, fixes it.

2022-10-11 05:39 UTC, tuichenchuxin approved these changes

2022-10-11 05:53 UTC, strongduanmu requested changes

2022-10-11 05:53 UTC, strongduanmu commented on features/sharding/core/src/main/java/org/apache/shardingsphere/sharding/route/engine/type/standard/ShardingStandardRoutingEngine.java
> +                result = result || ((CommonSQLStatementContext<?>) sqlStatementContext).containsHintShardingValue(each);
Can you use guard clause here? Just like:

```java
if (CommonSQLStatementContext<?>) sqlStatementContext).containsHintShardingValue(each) {
return true;
}
```

2022-10-12 00:28 UTC, strongduanmu approved these changes
Good job, merged.

2022-10-12 00:29 UTC, merged