Unit test cases for the ReflectiveUtil
apache/shardingsphere pull request #21778
Opened 2022-10-26 12:44 UTC by ishu-thakur

Fixes #21746.

Changes proposed in this pull request:
 Adding the Unit tests for the ReflectiveUtil by adding new test class file as ReflectiveUtilTest under reflect package.

2022-10-26 12:49 UTC, ishu-thakur commented
@sandynz @strongduanmu Please review this PR :)

2022-10-28 02:17 UTC, sandynz requested changes

2022-10-28 02:17 UTC, sandynz commented on infra/util/src/test/java/org/apache/shardingsphere/infra/util/reflect/ReflectiveUtilTest.java
> +    public static final class ReflectiveFixture {
It's better to use `private` for inner class

2022-10-29 02:13 UTC, sandynz approved these changes
Thanks for your contribution

2022-10-29 02:13 UTC, merged