Refactor migration inventory finished percentage
apache/shardingsphere pull request #22171
Opened 2022-11-14 11:16 UTC by azexcy

Changes proposed in this pull request:
  - Refactor migration inventory finished percentage
  - Add unit test

---

Before committing this PR, I'm sure that I have checked the following options:
- [ ] My code follows the [code of conduct](https://shardingsphere.apache.org/community/en/involved/conduct/code/) of this project.
- [ ] I have self-reviewed the commit code.
- [ ] I have (or in comment I request) added corresponding labels for the pull request.
- [ ] I have passed maven check locally : `./mvnw clean install -B -T1C -Dmaven.javadoc.skip -Dmaven.jacoco.skip -e`.
- [ ] I have made corresponding changes to the documentation.
- [ ] I have added corresponding unit tests for my changes.

2022-11-14 11:21 UTC, azexcy commented
```
mysql> show migration status 'j0101395cd93b2cfc189f29958b8a0342e882';
+------+-------------+------------------------+--------+-------------------------+-------------------------------+--------------------------+---------------+
| item | data_source | status                 | active | processed_records_count | inventory_finished_percentage | incremental_idle_seconds | error_message |
+------+-------------+------------------------+--------+-------------------------+-------------------------------+--------------------------+---------------+
| 0    | sysbench_ds | EXECUTE_INVENTORY_TASK | true   | 1812000                 | 9                             |                          |               |
+------+-------------+------------------------+--------+-------------------------+-------------------------------+--------------------------+---------------+
1 row in set (0.02 sec)

mysql> show migration status 'j0101395cd93b2cfc189f29958b8a0342e882';
+------+-------------+------------------------+--------+-------------------------+-------------------------------+--------------------------+---------------+
| item | data_source | status                 | active | processed_records_count | inventory_finished_percentage | incremental_idle_seconds | error_message |
+------+-------------+------------------------+--------+-------------------------+-------------------------------+--------------------------+---------------+
| 0    | sysbench_ds | EXECUTE_INVENTORY_TASK | true   | 10864000                | 54                            |                          |               |
+------+-------------+------------------------+--------+-------------------------+-------------------------------+--------------------------+---------------+
1 row in set (0.17 sec)

mysql> show migration status 'j0101395cd93b2cfc189f29958b8a0342e882';
+------+-------------+------------------------+--------+-------------------------+-------------------------------+--------------------------+---------------+
| item | data_source | status                 | active | processed_records_count | inventory_finished_percentage | incremental_idle_seconds | error_message |
+------+-------------+------------------------+--------+-------------------------+-------------------------------+--------------------------+---------------+
| 0    | sysbench_ds | EXECUTE_INVENTORY_TASK | true   | 19996000                | 99                            |                          |               |
+------+-------------+------------------------+--------+-------------------------+-------------------------------+--------------------------+---------------+
1 row in set (0.05 sec)

mysql> show migration status 'j0101395cd93b2cfc189f29958b8a0342e882';
+------+-------------+--------------------------+--------+-------------------------+-------------------------------+--------------------------+---------------+
| item | data_source | status                   | active | processed_records_count | inventory_finished_percentage | incremental_idle_seconds | error_message |
+------+-------------+--------------------------+--------+-------------------------+-------------------------------+--------------------------+---------------+
| 0    | sysbench_ds | EXECUTE_INCREMENTAL_TASK | true   | 20000000                | 100                           |                          |               |
+------+-------------+--------------------------+--------+-------------------------+-------------------------------+--------------------------+---------------+
1 row in set (0.03 sec)
```

2022-11-14 11:45 UTC, sandynz requested changes

2022-11-14 11:45 UTC, sandynz commented on features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/migration/distsql/handler/query/ShowMigrationJobStatusQueryResultSet.java
> +            InventoryIncrementalJobItemProgress jobItemProgress = jobItemInfo.getJobItemProgress();
It's better to keep use `each` for common methods, it's enough

2022-11-14 11:45 UTC, sandynz commented on features/sharding/distsql/handler/src/main/java/org/apache/shardingsphere/migration/distsql/handler/query/ShowMigrationJobStatusQueryResultSet.java
> +                result.add(jobItemInfo.getIncrementalIdleSeconds());
It's `null != jobItemProgress` in if condition, but it use `jobItemInfo` here, it's not clear enough as before

2022-11-14 11:45 UTC, sandynz commented on kernel/data-pipeline/api/src/main/java/org/apache/shardingsphere/data/pipeline/api/pojo/MigrationJobItemInfo.java
> +public final class MigrationJobItemInfo extends InventoryIncrementalJobItemInfo {
Looks it's not necessary to create `MigrationJobItemInfo`, we could keep them in `InventoryIncrementalJobItemInfo` for common usage

2022-11-14 11:45 UTC, sandynz commented on kernel/data-pipeline/core/src/main/java/org/apache/shardingsphere/data/pipeline/scenario/migration/MigrationJobAPIImpl.java
> +    public List<InventoryIncrementalJobItemInfo> getJobItemInfos(final String jobId) {
Could keep it in `AbstractInventoryIncrementalJobAPIImpl` and extend it for common usage

2022-11-15 01:56 UTC, sandynz approved these changes

2022-11-15 01:56 UTC, merged