support for Repeat function
apache/shardingsphere pull request #24470
Opened 2023-03-05 17:38 UTC by kanha-gupta

Fixes #24398 .

Changes proposed in this pull request:
  
support for REPEAT function

Before committing this PR, I'm sure that I have checked the following options:
- [ ] My code follows the [code of conduct](https://shardingsphere.apache.org/community/en/involved/conduct/code/) of this project.
- [ ] I have self-reviewed the commit code.
- [ ] I have (or in comment I request) added corresponding labels for the pull request.
- [ ] I have passed maven check locally : `./mvnw clean install -B -T1C -Dmaven.javadoc.skip -Dmaven.jacoco.skip -e`.
- [ ] I have made corresponding changes to the documentation.
- [ ] I have added corresponding unit tests for my changes.

2023-03-05 17:42 UTC, kanha-gupta commented
@RaigorJiang @strongduanmu Please guide if the approach is fine ? if yes then i'll proceed with adding support for others too.

2023-03-06 03:54 UTC, strongduanmu requested changes
Hi @kanha-gupta, please remove useless `|` after `REPEAT`.

2023-03-06 04:04 UTC, strongduanmu requested changes

2023-03-06 04:04 UTC, strongduanmu commented on test/it/parser/src/main/resources/case/dml/select-expression.xml
> +      <projections start-index="7" stop-index="25">
Please keep the same indent as the other cases.

2023-03-06 13:29 UTC, complone approved these changes

2023-03-07 00:24 UTC, strongduanmu approved these changes
Thank you @kanha-gupta, merged.

2023-03-07 00:24 UTC, merged