Fix the error of incremental tasks caused by datetime containing zero value in MySQL
apache/shardingsphere pull request #25144
Opened 2023-04-12 12:00 UTC by azexcy

refer https://dev.mysql.com/doc/refman/8.0/en/datetime.html
MySQL may have the datetime value wiht '0000-00-00 00:00:00', but the value is illegal for `LocalDateTime` at java.

Changes proposed in this pull request:
  - Fix the error of incremental tasks caused by datetime containing zero value in MySQL
  - Fix MySQLClient always print error log when decode binlog failed.

---

Before committing this PR, I'm sure that I have checked the following options:
- [ ] My code follows the [code of conduct](https://shardingsphere.apache.org/community/en/involved/conduct/code/) of this project.
- [ ] I have self-reviewed the commit code.
- [ ] I have (or in comment I request) added corresponding labels for the pull request.
- [ ] I have passed maven check locally : `./mvnw clean install -B -T1C -Dmaven.javadoc.skip -Dmaven.jacoco.skip -e`.
- [ ] I have made corresponding changes to the documentation.
- [ ] I have added corresponding unit tests for my changes.

2023-04-12 12:42 UTC, sandynz requested changes

2023-04-12 13:04 UTC, sandynz commented on db-protocol/mysql/src/main/java/org/apache/shardingsphere/db/protocol/mysql/packet/binlog/row/column/value/time/MySQLDatetime2BinlogProtocolValue.java
> +        }
https://dev.mysql.com/doc/internals/en/date-and-time-data-type-representation.html is not available now, refer to https://stackoverflow.com/questions/36937211/how-datetime-values-are-stored-in-mysql for more details.

2023-04-12 13:05 UTC, sandynz commented on db-protocol/mysql/src/main/java/org/apache/shardingsphere/db/protocol/mysql/packet/binlog/row/column/value/time/MySQLDatetime2BinlogProtocolValue.java
> +        }
The sign bit might be needed

2023-04-13 02:17 UTC, azexcy commented on db-protocol/mysql/src/main/java/org/apache/shardingsphere/db/protocol/mysql/packet/binlog/row/column/value/time/MySQLDatetime2BinlogProtocolValue.java
> +        }
The official document not find currently, but i found some relate source code from https://github.com/mysql/mysql-server/blob/5.7/sql-common/my_time.c#L1783

<img width="652" alt="image" src="https://user-images.githubusercontent.com/101622833/231629876-ab01d0ec-b15d-44a5-9d85-329def80aeb9.png">

the first bit sign seem not related to time

2023-04-13 06:35 UTC, azexcy commented
I find a problem when init ShardingSphereDataSource, the parameter at `jdbcUrl` maybe not equals with `dataSourceProperties`

<img width="798" alt="image" src="https://user-images.githubusercontent.com/101622833/231673314-02f1e1fe-fd60-4c91-8ad5-12fdae27394a.png">

This may lead to results that do not match expectations

2023-04-13 13:03 UTC, sandynz approved these changes

2023-04-13 13:04 UTC, merged