Add unit tests for ShardingSphereTable
apache/shardingsphere pull request #25386
Opened 2023-04-28 04:55 UTC by 100paperkite

Fixes #25361

Changes proposed in this pull request:
  -

---

Before committing this PR, I'm sure that I have checked the following options:
- [x] My code follows the [code of conduct](https://shardingsphere.apache.org/community/en/involved/conduct/code/) of this project.
- [x] I have self-reviewed the commit code.
- [x] I have (or in comment I request) added corresponding labels for the pull request.
- [x] I have passed maven check locally : `./mvnw clean install -B -T1C -Dmaven.javadoc.skip -Dmaven.jacoco.skip -e`.
- [ ] I have made corresponding changes to the documentation.
- [x] I have added corresponding unit tests for my changes.

2023-04-28 07:41 UTC, strongduanmu requested changes

2023-04-28 07:41 UTC, strongduanmu commented on infra/common/src/test/java/org/apache/shardingsphere/infra/metadata/database/schema/model/ShardingSphereTableTest.java
> +
Please remove useless blank line.

2023-04-28 07:41 UTC, strongduanmu commented on infra/common/src/test/java/org/apache/shardingsphere/infra/metadata/database/schema/model/ShardingSphereTableTest.java
> +
Please remove useless blank line.

2023-04-28 07:41 UTC, strongduanmu commented on infra/common/src/test/java/org/apache/shardingsphere/infra/metadata/database/schema/model/ShardingSphereTableTest.java
> +
Please remove useless blank line.

2023-04-28 07:41 UTC, strongduanmu commented on infra/common/src/test/java/org/apache/shardingsphere/infra/metadata/database/schema/model/ShardingSphereTableTest.java
> +
Please remove useless blank line.

2023-04-28 07:42 UTC, strongduanmu requested changes

2023-04-28 07:42 UTC, strongduanmu commented on infra/common/src/test/java/org/apache/shardingsphere/infra/metadata/database/schema/model/ShardingSphereTableTest.java
> +    void putColumn() {
Please rename test method to assertPutColumn.

2023-05-02 05:51 UTC, strongduanmu approved these changes

2023-05-02 05:52 UTC, strongduanmu requested changes

2023-05-02 05:52 UTC, strongduanmu commented on infra/common/src/test/java/org/apache/shardingsphere/infra/metadata/database/schema/model/ShardingSphereTableTest.java
> +
Please remove useless blank line.

2023-05-02 05:56 UTC, 100paperkite commented on infra/common/src/test/java/org/apache/shardingsphere/infra/metadata/database/schema/model/ShardingSphereTableTest.java
> +
Sorry for missing that. I removed it :)

2023-05-02 23:33 UTC, strongduanmu approved these changes

2023-05-02 23:34 UTC, merged

2023-05-02 23:34 UTC, strongduanmu commented
@100paperkite Good job, merged.