Optimized sqlParser to support examples from MySQL Test Suite.
apache/shardingsphere pull request #25580
Opened 2023-05-11 11:20 UTC by iamhucong

Issue [25535](https://github.com/apache/shardingsphere/issues/25535).

Changes proposed in this pull request:
  - Optimize DALStatement.g4 histogram checkTable.

---

Before committing this PR, I'm sure that I have checked the following options:
- [ ] My code follows the [code of conduct](https://shardingsphere.apache.org/community/en/involved/conduct/code/) of this project.
- [ ] I have self-reviewed the commit code.
- [ ] I have (or in comment I request) added corresponding labels for the pull request.
- [ ] I have passed maven check locally : `./mvnw clean install -B -T1C -Dmaven.javadoc.skip -Dmaven.jacoco.skip -e`.
- [ ] I have made corresponding changes to the documentation.
- [ ] I have added corresponding unit tests for my changes.

2023-05-11 12:28 UTC, iamhucong commented
@strongduanmu Hello, could you please review this pull request for me? Thank you.

2023-05-12 01:57 UTC, strongduanmu requested changes

2023-05-12 01:57 UTC, strongduanmu commented on test/it/parser/src/main/resources/sql/supported/dal/check-table.xml
> +    <sql-case id="check_tables_2" value="CHECK TABLES t_order,t_order_item" db-types="MySQL" />
Please rename it to check_multi_tables.

2023-05-12 04:50 UTC, strongduanmu approved these changes

2023-05-12 04:50 UTC, merged