Add unit test for ProjectionUtils public method
apache/shardingsphere pull request #27331
Opened 2023-07-20 09:08 UTC by pandalee99

Fixes #27317.
add a test class ProjectionUtilsTest
and two test  method:
  - ProjectionUtilsTest#getColumnLabelFromAlias
  - ProjectionUtilsTest#getColumnNameFromFunction

---

Before committing this PR, I'm sure that I have checked the following options:
- [x] My code follows the [code of conduct](https://shardingsphere.apache.org/community/en/involved/conduct/code/) of this project.
- [x] I have self-reviewed the commit code.
- [ ] I have (or in comment I request) added corresponding labels for the pull request.
- [x] I have passed maven check locally : `./mvnw clean install -B -T1C -Dmaven.javadoc.skip -Dmaven.jacoco.skip -e`.
- [ ] I have made corresponding changes to the documentation.
- [x] I have added corresponding unit tests for my changes.

2023-07-20 10:07 UTC, pandalee99 commented
> The operation was canceled.

strange.

2023-07-23 13:43 UTC, strongduanmu requested changes

2023-07-23 13:43 UTC, strongduanmu commented on infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/segment/select/projection/util/ProjectionUtilsTest.java
> +public class ProjectionUtilsTest {
Please remove public modifier for ProjectionUtilsTest.

2023-07-23 13:43 UTC, strongduanmu commented on infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/segment/select/projection/util/ProjectionUtilsTest.java
> +        assertThat(ProjectionUtils.getColumnLabelFromAlias(alias, databaseType), is(alias.getValue()));
Can you remove alias and new IdentifierValue here directly?

2023-07-23 13:43 UTC, strongduanmu commented on infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/segment/select/projection/util/ProjectionUtilsTest.java
> +        assertThat(ProjectionUtils.getColumnLabelFromAlias(alias, databaseType), is(alias.getValue().toLowerCase()));
Can you change expected string to constant?

2023-07-23 13:43 UTC, strongduanmu commented on infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/segment/select/projection/util/ProjectionUtilsTest.java
> +        databaseType = new PostgreSQLDatabaseType();
Same suggestion with databaseType.

2023-07-24 03:24 UTC, pandalee99 commented on infra/binder/src/test/java/org/apache/shardingsphere/infra/binder/segment/select/projection/util/ProjectionUtilsTest.java
> +        databaseType = new PostgreSQLDatabaseType();
thanks,i can

2023-07-24 03:43 UTC, pandalee99 commented
CI / CI have problem
> Error:   package org.apache.shardingsphere.infra.util.quote does not exist
I didn't change this class.  but he tell me have problem.
so,what should I do.

2023-07-24 08:48 UTC, strongduanmu commented
You can merge master branch code.

2023-07-28 14:09 UTC, pandalee99 commented
i am done .maybe,can be approve

2023-08-15 05:58 UTC, strongduanmu approved these changes

2023-08-15 05:58 UTC, merged