Support for WithSegment
apache/shardingsphere pull request #28555
Opened 2023-09-22 23:18 UTC by kanha-gupta

Ref #28328 

- Support for SQLServer conversion
- Support for WithSegment
- Testcase addition (pending)

2023-09-23 23:14 UTC, strongduanmu approved these changes
Hi @kanha-gupta, can you take a look at checkstyle?

2023-09-23 23:15 UTC, strongduanmu requested changes
Hi @kanha-gupta, can you take a look at checkstyle?

2023-09-25 13:09 UTC, kanha-gupta commented
@strongduanmu With Converter Class is made to convert various SQL statements such as Insert, delete, update therefore Constructor takes parameters of WithSegment and query(SqlNode)

2023-09-26 03:26 UTC, strongduanmu approved these changes

2023-09-26 03:26 UTC, merged