Increase Support for dmlTableClause for Oracle
apache/shardingsphere pull request #28934
Opened 2023-11-04 00:36 UTC by kanha-gupta

Ref #27377 

Changes proposed in this pull request:
  -

---

Before committing this PR, I'm sure that I have checked the following options:
- [ ] My code follows the [code of conduct](https://shardingsphere.apache.org/community/en/involved/conduct/code/) of this project.
- [ ] I have self-reviewed the commit code.
- [ ] I have (or in comment I request) added corresponding labels for the pull request.
- [ ] I have passed maven check locally : `./mvnw clean install -B -T1C -Dmaven.javadoc.skip -Dmaven.jacoco.skip -e`.
- [ ] I have made corresponding changes to the documentation.
- [ ] I have added corresponding unit tests for my changes.

2023-11-11 12:23 UTC, strongduanmu requested changes

2023-11-11 12:23 UTC, strongduanmu commented on kernel/sql-federation/optimizer/src/main/java/org/apache/shardingsphere/sqlfederation/optimizer/converter/segment/from/impl/SimpleTableConverter.java
> +            names.add(segment.getAt().get().getValue());
Can you check segment.getAt().isPresent() before call get method?

2023-11-11 23:08 UTC, kanha-gupta commented
@strongduanmu Changes are done, Please review :)

2023-11-13 01:02 UTC, strongduanmu approved these changes
Looks great, merged.

2023-11-13 01:02 UTC, merged