Update authentication.cn.md
apache/shardingsphere pull request #8716
Opened 2020-12-22 06:54 UTC by liuqian1990

Fixes #ISSUSE_ID.

Changes proposed in this pull request:
-
-
-

2020-12-22 09:21 UTC, terrymanu requested changes

2020-12-22 09:21 UTC, terrymanu commented on docs/document/content/user-manual/shardingsphere-proxy/configuration/authentication.cn.md
> +      password: root # 自定义用户名密码
It is better for 自定义用户名`的`密码

2020-12-22 09:21 UTC, terrymanu commented
Can you check english doc too?

2020-12-22 12:02 UTC, liuqian1990 commented
english doc No error

2020-12-23 11:36 UTC, terrymanu commented
Can you update your change which followed by code review suggestion?

2021-01-20 05:26 UTC, terrymanu approved these changes

2021-01-20 05:26 UTC, merged