add integration-test (dql dml) for broadcast feature
apache/shardingsphere pull request #9126
Opened 2021-01-22 06:19 UTC by JiekerTime

2021-01-22 15:07 UTC, terrymanu requested changes

2021-01-22 15:07 UTC, terrymanu commented on shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-suite/src/test/java/org/apache/shardingsphere/test/integration/engine/it/BatchIT.java
> +            }
It is not a good design for add some concrete codes in the engine.

2021-01-24 06:03 UTC, tristaZero requested changes

2021-01-24 06:03 UTC, tristaZero commented on shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-suite/src/test/resources/cases/dql/dql-integration-test-cases.xml
> +<!--    <test-case sql="SELECT * FROM t_broadcast_table">-->
Is there no needed to have this test?

2021-01-26 08:40 UTC, closed without merging