feature: truncate table in oracle.
apache/shardingsphere pull request #9306
Opened 2021-02-04 01:28 UTC by wgy8283335

Fixes #6480.

Changes proposed in this pull request:
- add grammar for truncate table

2021-02-04 03:20 UTC, tristaZero requested changes

2021-02-04 03:20 UTC, tristaZero commented on shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-oracle/src/main/antlr4/imports/oracle/DDLStatement.g4
> +    ;
A new line is needed here.

2021-02-06 03:38 UTC, wgy8283335 commented on shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-oracle/src/main/antlr4/imports/oracle/DDLStatement.g4
> +    ;
I've fix this.

2021-02-07 02:41 UTC, tristaZero reviewed
Looks great.

2021-02-07 02:41 UTC, tristaZero approved these changes

2021-02-07 02:41 UTC, merged