Refactor: move packages
apache/shardingsphere pull request #9547
Opened 2021-03-01 10:07 UTC by dmsolr

Fixes #ISSUSE_ID.

Changes proposed in this pull request:
-
-
-

2021-03-01 11:45 UTC, terrymanu approved these changes

2021-03-01 11:46 UTC, terrymanu requested changes
There are some compile error in CI

2021-03-02 02:51 UTC, yu199195 commented
this pr  can merged, other ci error is dependent  jar  could not be download. @terrymanu

2021-03-03 03:43 UTC, yu199195 approved these changes

2021-03-03 04:43 UTC, terrymanu approved these changes

2021-03-03 04:43 UTC, merged