Refactor eventbus and distsql handler
apache/shardingsphere pull request #9731
Opened 2021-03-18 10:04 UTC by juaby

Fixes #ISSUSE_ID.

Changes proposed in this pull request:
- RT

2021-03-20 03:55 UTC, tristaZero requested changes

2021-03-20 03:55 UTC, tristaZero commented on shardingsphere-infra/shardingsphere-infra-common/src/main/java/org/apache/shardingsphere/infra/eventbus/CompletableEventService.java
> +        } catch (IllegalAccessException | InvocationTargetException e) {
final one?

2021-03-20 03:55 UTC, tristaZero commented on shardingsphere-infra/shardingsphere-infra-common/src/main/java/org/apache/shardingsphere/infra/eventbus/ShardingSphereEventBus.java
> +    public <T> void register(final T target) {
Where is this function called?

2021-03-20 03:59 UTC, tristaZero requested changes

2021-03-20 03:59 UTC, tristaZero commented on shardingsphere-infra/shardingsphere-infra-common/src/main/java/org/apache/shardingsphere/infra/eventbus/CompletableEventService.java
> +            Class<?>[] parameterTypes = method.getParameterTypes();
Is it supposed to remove all `@Subscribe` annotation from `renew()` of target classes?

2021-03-22 07:54 UTC, juaby commented on shardingsphere-infra/shardingsphere-infra-common/src/main/java/org/apache/shardingsphere/infra/eventbus/CompletableEventService.java
> +        } catch (IllegalAccessException | InvocationTargetException e) {
Fixed

2021-03-22 08:58 UTC, tristaZero requested changes

2021-03-22 08:58 UTC, tristaZero commented on shardingsphere-infra/shardingsphere-infra-common/src/main/java/org/apache/shardingsphere/infra/eventbus/CompletableEvent.java
> +public class CompletableEvent<E> {
final one?

2021-03-23 06:36 UTC, juaby commented on shardingsphere-infra/shardingsphere-infra-common/src/main/java/org/apache/shardingsphere/infra/eventbus/CompletableEvent.java
> +public class CompletableEvent<E> {
Fixed

2021-03-23 06:47 UTC, closed without merging